data <- read.csv("cours1.csv",fileEncoding = "UTF-8")
tab <- table(data$appétence.codage..1.fort.4.mauvais)
barplot(tab, col = heat.colors(5), border = NA, xlab = "appétence, (1 oui - 4 non)")
barplot(tab)
tab <- table(data$Prénom)
tab <- table(data$nom)
tab <- table(data$adresse.mail)
tab<-table(data$X44223)
tab<-table(data$passé)
tab<-table(data$présent)
tab<-table(data$futur)
tab<-table(data$Niveau.de.codage.de.0.à.5)
barplot(tab,col = heat.colors(10))
barplot(tab,border = NA)
barplot(tab,col = heat.colors(4))
barplot(tab,border = NA)
barplot(tab,legend.text = T)
barplot(tab,main = "présent des étudiants")
str(data)
tab<-table(data$futur)
etik<-names(tab)
names(tab)
barplot(tab,names.arg = names(tab))
barplot(tab,las=2)
motif<-grep("rba",data$futur)
data$futur[motif]
data$futur[motif]<-"urbanisme"
png(height = 800, width = 600, filename = "img/resultat.png")

